# Generated by Django 4.1.3 on 2023-02-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_Name', models.TextField(max_length=255)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Option',
            new_name='Topic',
        ),
    ]
