# Generated by Django 4.1.3 on 2023-02-14 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0002_teams_rename_option_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
    ]
