# Generated by Django 4.1.3 on 2023-02-15 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0004_alter_topic_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='qustion',
            new_name='question',
        ),
    ]
