# Generated by Django 4.1.7 on 2023-03-12 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0008_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeopardy.points'),
        ),
    ]
