# Generated by Django 4.1.7 on 2023-03-12 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0009_alter_question_points'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
