# Generated by Django 4.1.7 on 2023-03-12 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0010_delete_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Points',
            new_name='Point',
        ),
    ]
