# Generated by Django 4.1.7 on 2023-03-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0011_rename_points_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='isAnswerd',
            field=models.BooleanField(default=False),
        ),
    ]
