# Generated by Django 4.1.7 on 2023-03-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0012_question_isanswerd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='isAnswerd',
        ),
        migrations.RemoveField(
            model_name='team',
            name='score',
        ),
        migrations.AddField(
            model_name='team',
            name='qustionsAnsered',
            field=models.ManyToManyField(to='jeopardy.question'),
        ),
    ]
