# Generated by Django 4.1.7 on 2023-03-12 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0013_remove_question_isanswerd_remove_team_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_Name',
            new_name='teamName',
        ),
    ]
