# Generated by Django 4.1.7 on 2023-03-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0015_alter_team_teamname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='qustionsAnsered',
            field=models.ManyToManyField(blank=True, null=True, to='jeopardy.question'),
        ),
    ]
