# Generated by Django 4.1.7 on 2023-03-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0017_alter_team_qustionsansered'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_turn',
            field=models.BooleanField(default=False),
        ),
    ]
