# Generated by Django 4.1.7 on 2023-03-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0018_team_is_turn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='qustionsAnsered',
        ),
        migrations.AddField(
            model_name='team',
            name='qustionsCorrect',
            field=models.ManyToManyField(blank=True, related_name='correct', to='jeopardy.question'),
        ),
        migrations.AddField(
            model_name='team',
            name='qustionsIncorrect',
            field=models.ManyToManyField(blank=True, related_name='incorect', to='jeopardy.question'),
        ),
    ]
