# Generated by Django 4.1.7 on 2023-03-12 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0019_remove_team_qustionsansered_team_qustionscorrect_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='qustionsCorrect',
            new_name='correct',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='qustionsIncorrect',
            new_name='incorrect',
        ),
    ]
