# Generated by Django 4.1.7 on 2023-03-12 19:29

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0020_rename_qustionscorrect_team_correct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='is_turn',
        ),
        migrations.AddField(
            model_name='team',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
