# Generated by Django 4.1.7 on 2023-03-17 08:57

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0021_remove_team_is_turn_team_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='color',
            field=colorfield.fields.ColorField(default='#EC008C', image_field=None, max_length=18, samples=None),
        ),
    ]
