# Generated by Django 4.1.7 on 2023-03-22 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0023_alter_team_incorrect'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jeopardy.point'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jeopardy.topic'),
        ),
    ]
